name: meta_weather_api
description: A Dart package which manages MetaWeather API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.1.0
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  mocktail: ^0.3.0
  test: ^1.20.1
dependencies: 
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0
