name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.1.0
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
  test: ^1.19.2
dependencies: 
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  meta_weather_api: 
    path: ../meta_weather_api
